version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      windows-app-sdk:
        patterns: ["Microsoft.Windows*", "Microsoft.WindowsAppSDK*"]
      community-toolkit:
        patterns: ["CommunityToolkit.*"]
      test:
        patterns: ["xunit*", "Microsoft.NET.Test.Sdk", "coverlet*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
